### ISSUE TITLE
Testing Editing BNK Audio Files

### ISSUE THREAD

**Issue by abso1utezer0** [andrewplus/epic-mickey-docs#7]
https://github.com/EtiTheSpirit/BNKReplacer

**Comment by abso1utezer0** [comment]
If this works with Epic Mickey I believe there should be a guide on the page.

**Comment by andrewplus** [comment]
Has this been attempted yet?

**Comment by abso1utezer0** [comment]
I have attempted it. Unfortunately it only supports the new format of Wwise (wem) seen after 2012 instead of the pre 2012 version EM1 uses (lwav).
